language: ruby
sudo: false
cache: bundler
bundler_args: --without guard
script: 'bundle exec rake ci'
rvm:
  - 2.0
  - 2.1
  - 2.2
  - rbx-2
  - jruby
  - jruby-head
  - ruby-head
env:
  global:
    - CODECLIMATE_REPO_TOKEN=89c1e3c7e6e1459a80d4aebc0db703e681217c93e380ac6e435003ffb364323d
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
